### ISSUE TITLE
Cards Upgrade

### ISSUE THREAD

**Issue by sarhatabaot** [sarhatabaot/TradingCards#185]
Allow players to "upgrade" their cards to a different rarity.
`/cards upgrade` while holding cards from a certain rarity will upgrade them to another rarity.
`/cards upgrade <amount/max>` will attempt to upgrade the amount of cards to another rarity. 

For example:
```yaml
upgrades:
   upgrade-1:
     required: common:3:default
     result: uncommon:1:default
```

`/cards upgrade` - While having 3 common cards in your hand from the common & default series, will upgrade once to a random uncommon card from the default series.
`/cards upgrade 2` - Will require 6 common cards, and will upgrade to 2 random cards from the default series.

**Additional context**
First requested in #61
